x = input("give me a verb, NOW!")
y = input("i demand another verb!!!")
r = input("now my pookie provide me with a noun:)")
t = input("ugh now i need A NUMBERRRR :(")
v = input("surprise surprise now i need a... celebirty")
print(f"it was {r} day at school, and {v} was ready for lunch. But when he/she {x} outside to eat, {t} birds {y} her food.")